### ISSUE TITLE
does this make sense, _no found data for ebird_

### ISSUE THREAD

**Issue by sckott** [ropensci/spocc#111]
ebird doesn't provide any data on how many records were found in any given query AFAIK, so in the newer print method we have for what's returned from `occ()` we have

```r
occ(query = 'Accipiter striatus', from=c('gbif','bison','inat','ebird','ecoengine'), limit=10)
```

```r
Searched: gbif, bison, inat, ebird, ecoengine
Occurrences - Found: 1,114,773 (no found data for ebird), Returned: 50
Search type: Scientific
  gbif: Accipiter striatus (10)
  bison: Accipiter striatus (10)
  inat: Accipiter striatus (10)
  ebird: Accipiter striatus (10)
  ecoengine: Accipiter striatus (10)
```

does this

> (no found data for ebird)

message make sense? or too confusing?  i feel like not saying anything would be pretty misleading, but just not sure about this. We could just mention this problem in the documentation only and not include this message

**Comment by sckott** [comment]
ping @karthik @cboettig

**Comment by sckott** [comment]
i think antweb is the same with no found data given in the api response

**Comment by cboettig** [comment]
The above code block still seems to suggest that ebird returned `10` results, despite saying `no found data`.  Also am I missing some cowsay or something or should the message read `no data found`?

**Comment by sckott** [comment]
hmm, i thought this would be confusing.  

the `no found data` refers to the `Found` bit, that is, number of records in the DB, not those returned, Whereas the `Returned` bit says how many were actually returned. 

ebird and antweb don't return any data AFAIK on how many records were found int their database, so we can't report that in the summary number

maybe it's easier to just explain it in the documentation?

**Comment by cboettig** [comment]
Ah ha! I see what you mean now, sorry.  Yeah, that's confusing.  How about something more like:

```
Found >= 1,114,773 * records
...
...
* : spocc cannot estimate how many additional records were found but not returned on ebird or antweb.
```

I'm generally against confusing error messages that require documentation to understand them ;-).  If the message isn't going to make sense without the documentation, then it should just say: `read the documentation`.

**Comment by sckott** [comment]
@cboettig that's a good idea to print that kidn of footnote message

**Comment by karthik** [comment]
> i think antweb is the same with no found data given in the api response - or am i wrong here?

It does return, but I'm not sure if I include that in the return object. I'll check.

```r
> z <- aw_data(min_elevation = 1500, max_elevation = 2000)
Query contains 35886 results. First 1000 retrieved. Use the offset argument to retrieve more 

35886 results available for query.
```

> I'm generally against confusing error messages that require documentation to understand them ;-).

I'm with @cboettig here. No found data is confusing to me requiring further documentation lookup. I like Carl's suggestion.

**Comment by karthik** [comment]
@sckott AntWeb does return a total available. In the example above, `z$count` will return `35886`

**Comment by sckott** [comment]
k, thanks, i'll add that in

**Comment by sckott** [comment]
this should be good now, closing
