### ISSUE TITLE
bison has been buggy for a while now, perhaps remove temporarily

### ISSUE THREAD

**Issue by sckott** [ropensci/spocc#115]
This is incredibly frustrating. BISON API can be down for days at a time, old URLs have changed to new ones, and new ones are often incredibly slow or don't work at all.

**Comment by emhart** [comment]
Is it possible to run a test fxn and automatically disable it for a session and print a warning instead of irrevocably disabling it?

**Comment by sckott** [comment]
perhaps, there's just no way to know when they will be up and running again, and i imagine there are users out there frustrated by this, but I could just set a timeout maybe on bison fxn so that it fails after a certain time

**Comment by sckott** [comment]
on cran now
