### ISSUE TITLE
inat breakin'

### ISSUE THREAD

**Issue by sckott** [ropensci/spocc#119]
```r
out <- occ(query='Setophaga caerulescens', from='inat', limit=50)
out$inat

#> Species [Setophaga caerulescens (50)] 
#> First 10 rows of [Setophaga_caerulescens]
#> 
#> Error in data.frame(name = z$name, longitude = z$longitude, latitude = z$latitude,  : 
#>   arguments imply differing number of rows: 0, 50
```

**Comment by emhart** [comment]
Sounds like a bad country song... :guitar:

Looks like some of the field names have changed coming back from the API:

```R
vp_obs <- get_inat_obs(query="vernal pool")
head(vp_obs$Species.guess)
```
This will return a `NULL`
but `vp_obs$species_guess` does work

That's my first guess as to the problem.  I can try and push a fix tonight if you don't get to it today.

**Comment by sckott** [comment]
right, figured it was col. name changes. 

working on this anyway, can fix today or tomorrow

**Comment by sckott** [comment]
woops, forgot i was working on dev branch, actually fine
