### ISSUE TITLE
Split off mapping/etc. functions to a spocc utilities package?

### ISSUE THREAD

**Issue by sckott** [ropensci/spocc#132]
Anyone mind if I do this?

The package is complicated enough with lots of moving parts just considering the pkgs to get data (e.g., vertnet, antweb, etc.).  

Could roll out a new pkg `spoccutils` with any data cleaning functions, mapping functions, etc. 

This would make `spocc` easier to install, lighter weight, easier to maintain. 

Thoughts. @ropensci/owners

**Comment by sckott** [comment]
Im dropping `rgdal`, `rgeos`, and `maptools`, which also makes `spocc` simpler #131

**Comment by karthik** [comment]
Sounds great to me. I'll work on finishing that mapbox package soon so we can remove all the separate interactive map calls in each one. 




Lean is good.

**Comment by sckott** [comment]
cool^3

**Comment by sckott** [comment]
done
