### ISSUE TITLE
gbif not returning eventDate -> occ2df erroring

### ISSUE THREAD

**Issue by goldingn** [ropensci/spocc#141]
Hi Scott,

I spotted what looks like a bug with some queries to gbif.

The following returns two hits:
```r
(o <- occ(query = 'Culex modestus',
         geometry = c(-11, 49.5, 2.5, 61),
         from = 'gbif',
         limit = 500))
```
`Searched: gbif
Occurrences - Found: 2, Returned: 2
Search type: Scientific
  gbif: Culex modestus (2)`

but when turning them into a data.frame I get this error:
```r
df <- occ2df(o)
```
`Error in [.data.frame(x, , c("name", "longitude", "latitude", "prov",  : 
  undefined columns selected`

Apparently it's because this query to gbif doesn't return an `eventDate` column, though I couldn;t tell you why!
```r
nm <- colnames(o$gbif$data$Culex_modestus)
(spocc:::datemap$gbif)
```
`[1] "eventDate"`
```r
grep('eventDate', nm)
```
`integer(0)`

I don't know if there's anything you can do with queries that don't return any dates - maybe just handle the error?

Anyway, great work on this package - it's incredibly useful!

**Comment by sckott** [comment]
thanks @goldingn - what version of `spocc` and `rgbif` are you using

**Comment by goldingn** [comment]
spocc is version 0.3.2, fresh from CRAN today

rgbif is 0.8.8

**Comment by sckott** [comment]
thanks, looking

**Comment by goldingn** [comment]
:+1:

**Comment by sckott** [comment]
@goldingn try reinstalling and see if it works now, it should 

`devtools::install_github("ropensci/spocc")`

**Comment by goldingn** [comment]
Like a charm - thanks for fixing this so quickly!

**Comment by sckott** [comment]
np, glad it works for you too
