### ISSUE TITLE
bison results in occ2df

### ISSUE THREAD

**Issue by timcdlucas** [ropensci/spocc#144]
I'm getting an error when getting results from bison.

    > s <- occ(query = 'Haliaeetus leucocephalus', geometry = c(-180, -90, 180, 90), from = 'bison', limit = 1000)
    > s

    Searched: bison
    Occurrences - Found: 227, Returned: 227
    Search type: Scientific
      bison: Haliaeetus leucocephalus (227)

    > occ2df(s)

    Error in `[.data.frame`(x, , c("name", "longitude", "latitude", "prov",  : 
      undefined columns selected

Seems like it probably something simple. I should probably just try and fix it myself. But I'm scared.

**Comment by sckott** [comment]
@timcdlucas thanks for the report!

what version of `spocc` are you using? I think that's fixed in the github dev version, can you `devtools::install_github("ropensci/spocc")` and try again

**Comment by timcdlucas** [comment]
Ok I'll have a look. Having a problem installing github version, but I think that's my messed up R install.

**Comment by sckott** [comment]
let me know if you need help

**Comment by sckott** [comment]
@timcdlucas were you able to install from github?

**Comment by timcdlucas** [comment]
Yup works fine. 

I found another bug yesterday but didn't submit an issue because I thought I should github install first. I'll try and remember what it was and check that as well. To do with dates when binding data from different databases.

**Comment by sckott** [comment]
Great, 

> To do with dates when binding data from different databases.

that may be fixed, just fixed something related to dates, #141

**Comment by sckott** [comment]
but if it's still a problem, do let me know!
