### ISSUE TITLE
query throwing error message

### ISSUE THREAD

**Issue by remsamp** [ropensci/spocc#151]
Here it is Scott, thanks!

occ(query = "Lepidepecreella cymba", from = 'obis', limit = 1000, obisopts = list(geometry = bbox2wkt(minx = (19.5), miny = (78.5), maxx = (19.5), maxy = (78.5))))

**Comment by sckott** [comment]
Thanks, looks like that search found no results, so a `results` key wasn't returned with the json data, so the internal fxns fail. fixed that on the last commit cd8f97f, install and try again

@remsamp

**Comment by sckott** [comment]
@remsamp let me know if it works for you now

**Comment by sckott** [comment]
also, for `geometry`, that's a top level parameter you can pass to `occ()` that will be handled correctly across data sources
