### ISSUE TITLE
occ query of ecoengine using spatial search does not return correct records

### ISSUE THREAD

**Issue by hmorzaria** [ropensci/spocc#158]
Setting bounding box and querying ecoengine

>>>
this.polygon 
[1] "POLYGON((-113.527516 20.929036 ,-113.357516 20.929036 ,-113.357516 21.099036 ,-113.527516 21.099036 ,-113.527516 20.929036))"

>>
spocc.recs = occ(geometry = this.polygon, from = c("ecoengine"), limit=10)

returns

>>>
Geometry [<geo1> (10)] 
                    name longitude latitude      prov    type
1  Hesperoyucca whipplei -118.6127  36.9814 ecoengine Feature
2   Keckiella breviflora -118.6127  36.9814 ecoengine Feature

which are not within the bounding box

**Comment by sckott** [comment]
thanks for your question. What version of R and operating system do you have, and what version of `spocc`

**Comment by sckott** [comment]
We have to make a bounding box internally, and looks like that's not happening correctly. I'll get a fix up soon

**Comment by sckott** [comment]
@hmorzaria Do you agree that you shouldn't get any results for that polygon?  Using the Ecoengine API directly I get no results, heres the query https://ecoengine.berkeley.edu/api/observations/?bbox=-113.527516,20.929036,-113.357516,22.099036&format=geojson

whereas a larger bounding box get some data, e.g, https://ecoengine.berkeley.edu/api/observations/?bbox=-113.527516,20.929036,-115.357516,22.099036&format=geojson

**Comment by karthik** [comment]
I've seen this issue before so I'll ping the ecoengine  API folks on this.

**Comment by sckott** [comment]
The bounding box thing is just a `spocc` problem. 

The no results though seems to just be no results for that query, unless there is supposed to be?

**Comment by karthik** [comment]
That's what I'll find out. Sometimes the API side does not pass on the bbox to the query itself.

**Comment by sckott** [comment]
oh, i see

**Comment by hmorzaria** [comment]
R version 3.2.1 (2015-06-18) -- "World-Famous Astronaut"
spocc 0.4
Windows 7
Yes, you were correct, no records were supposed to come out of that polygon query.

**Comment by sckott** [comment]
thanks @hmorzaria !

**Comment by sckott** [comment]
@hmorzaria try reinstalling from github `ginstall.packages("ropensci/spocc"); library("spocc")`, then try your eg again, should get no results

**Comment by sckott** [comment]
see updated install instructions, do refresh the page

**Comment by sckott** [comment]
fixed on the `spocc` side, closing - want to push this and other fixes to cran soon
