### ISSUE TITLE
error using ebird database

### ISSUE THREAD

**Issue by jesusNPL** [ropensci/spocc#161]
I'm using spocc to download data form multiple species from ebird, but when I use for example two common species such us Furnarius rufus and Tyrannus melancholicus return this error:

The line command
`(df <- occ(query = c('Furnarius rufus', 'Tyrannus melancholicus'), from = 'ebird', has_coords = T))`

The error returned

```r
Error in `$<-.data.frame`(`*tmp*`, "longitude", value = NA) : 
  replacement has 1 row, data has 0
```

Thanks in advance

J

**Comment by sckott** [comment]
thanks for the issue @jesusNPL  What version of `spocc` and `rebird` do you have installed?

**Comment by jesusNPL** [comment]
Dear Scott,

I'm using the version 0.2.9300 for rebird and 0.4.5.9500 for spocc.

Jesus

**Comment by sckott** [comment]
@jesusNPL try reinstalling like `devtools::install_github("ropensci/spocc")` There was a problem in the ebird parser where it wasn't processing results from ebird with no data. There was also a problem with `has_coords` that I fixed. 

The first species doesn't give any data back - is that what you expected?

**Comment by jesusNPL** [comment]
Dear Scott,

thanks for the quickly response, I reinstall from github as you suggested and now is working normally.

Cheers,

J

**Comment by sckott** [comment]
Great, glad it works now.
