### ISSUE TITLE
V8 dependency causing issues on Solaris

### ISSUE THREAD

**Issue by AugustT** [ropensci/spocc#162]
In the package `zoon` we use `spocc` in our vignette for demonstration. In CRAN checks I get this error on Solaris, V8, required for `spocc` cannot be installed.

```
    ERROR: configuration failed for package ‘V8’
    * removing ‘/home/ripley/R/Lib32/V8’
    Warning in install.packages(package, repos = "http://cran.rstudio.com") :
     installation of package 'V8' had non-zero exit status
    ERROR: dependency ‘V8’ is not available for package ‘rgbif’
    * removing ‘/home/ripley/R/Lib32/rgbif’
    Warning in install.packages(package, repos = "http://cran.rstudio.com") :
     installation of package 'rgbif' had non-zero exit status
    ERROR: dependencies ‘rgbif’, ‘V8’ are not available for package ‘spocc’
    * removing ‘/home/ripley/R/Lib32/spocc’
    Warning in install.packages(package, repos = "http://cran.rstudio.com") :
     installation of package 'spocc' had non-zero exit status
```

I see that `spocc` does not have any such issues reported on CRAN. Can you shed any light on if you came across this yourselves and if so how you got around it.

**Comment by sckott** [comment]
I don't know the answer off the top. Is that using win-builder? Which version, stable or dev R?

**Comment by AugustT** [comment]
Hi Scott, we have been looking at this in a bit more detail. We have spocc in our `%\VignetteDepends` which is why we think it throws an error for us. Looking at your vignette here you do not have vignette depends as you vignette does not run any code so you are probably getting around the issue that way. I also see you use `skiponcran()` in testing which is also going to hide these errors CRAN might have run into.

**Comment by sckott** [comment]
@AugustT Yeah, I do skip tests on cran. Vignette doesn't run because I do compile manually locally so I don't have to worry about it failing on CRAN - and burden users to build it on each install

for cran, I believe V8 just is not avail. on Solaris, right?  Yeah, i guess `spocc` gets by on CRAN because we don't run tests/vignette there - we do test on travis and appveyor though

let me know if anything else I can do

**Comment by AugustT** [comment]
Okay, thanks Scott this clears up the disparity between what I was seeing in our CRAN tests versus yours.
