### ISSUE TITLE
Feature suggestion: logo

### ISSUE THREAD

**Issue by maelle** [ropensci/spocc#188]
I'd suggest creating/having someone create a logo for `spocc` since it's such an ambitious and useful package. 

 This logo could be used:

* as _hex logo_ on :sparkles: stickers :sparkles: 

* and at the top of READMEs packages interfaced by `spocc` (like a badge, and when clicking one would land in a section of `spocc` README). 

* in a special footer for such packages as well.

When I think of `spocc` I think of animals and maps which I guess would make for a cool logo. If I remember correctly there's a way to re-generate something like rOpenSci logo so it could be used as a background to make it look a bit similar to rOpenSci logo.

**Comment by sckott** [comment]
notes:

- https://github.com/forwards/branding/blob/master/R/create_hex_sticker.R
- make image in magick, then sticker with hexsticker

```r
bird="http://phylopic.org/assets/images/submissions/c961d79e-eeba-40c1-a4da-f93f22b264c7.128.png"
beetle="http://phylopic.org/assets/images/submissions/fbb67694-0fd2-4e90-b88d-efab9cbac37c.128.png"
rabbit="http://phylopic.org/assets/images/submissions/1e15411c-5394-4a9d-a209-76c8ac0c331d.128.png"
```

**Comment by sckott** [comment]
yes, for the most part i think they are all CC0 - 

ah yes, good idea!

**Comment by maelle** [comment]
For when the package has a logo, `usethis::use_logo()` is great (to resize the logo -- using `magick`! --, to save it in the right location and to get the text to paste to the README). I used it last week for https://github.com/lockedata/pRojects

**Comment by sckott** [comment]
woops, pinged wrong issue - logo work in commit 719c8b97aed53be2f07be06f5b5d4dc95d18bc02 - @maelle any thoughts?  https://github.com/ropensci/spocc/blob/master/inst/logo/spocc.png code https://github.com/ropensci/spocc/blob/master/inst/logo/logo.R

**Comment by maelle** [comment]
It looks good 😀

I was about to mention the usethis function mentioned in https://github.com/ropensci/spocc/issues/188#issuecomment-421914492
