### ISSUE TITLE
Vignette title in pkgdown website

### ISSUE THREAD

**Issue by maelle** [ropensci/spocc#200]
making this question from #193 a separate issue.

I've thought a bit about it. Could you use `keep_yaml: true` in the YAML header of the actual vignette?

Besides, if I were to change the vignette, I wouldn't know how to build it, have you written up the workflow somewhere? Could it be built from Travis using `tic` btw?

**Comment by sckott** [comment]
> Could it be built from Travis using tic

ah maybe, worth looking into, i just don't want it to be built on installation by cran/users (you've heard my rant before i'm sure)
