### ISSUE TITLE
double occurances?

### ISSUE THREAD

**Issue by bwakkie** [ropensci/spocc#212]
As I know that research-grade data from iNaturalist flows towards GBIF. Does spocc take this into account?

**Comment by sckott** [comment]
thanks for your question @bwakkie - have you seen the `?spocc_duplicates` manual page? linked to from the pkg level man file as well `?spocc` or `?spocc-package` 

we don't try to deduplicate. we point the user to tools to help them deduplicate, and ask for any feedback on making it easier

**Comment by bwakkie** [comment]
Ah super ... how could I have missed that :)
