### ISSUE TITLE
maybe return photos in inat data?

### ISSUE THREAD

**Issue by sckott** [ropensci/spocc#214]
via https://discuss.ropensci.org/t/is-it-possible-to-download-inaturalist-images-with-spocc-rinat/1600

**Comment by keatonwilson** [comment]
This would be amazing - an incredibly useful addition to a number of projects our research group is working on (and likely others as well!).

**Comment by sckott** [comment]
thanks for the bump on this @keatonwilson  can you try it and let me know what you think? 

```r
remotes::install_github("ropensci/spocc@sidecar")
# reload R / i.e., quit, then restart R
library(spocc)
res <- occ(query = 'Danaus plexippus', from = 'inat', limit = 50)
data.table::rbindlist(res$inat$data$Danaus_plexippus$photos)
```

**Comment by keatonwilson** [comment]
Just got it working! Super useful - would be easy to bulk-download photos via R or command line for further analysis. This is a great addition - thank you!

**Comment by sckott** [comment]
great, glad it works. will be merged into master soon
