### ISSUE TITLE
error with occ2df

### ISSUE THREAD

**Issue by mgaynor1** [ropensci/spocc#242]
Error in allocate_column(df[[var]], nrows, dfs, var) : 
  Data frame column 'gadm' not supported by rbind_fill
In addition: Warning messages:
1: In data.table::rbindlist(data, use.names = TRUE, fill = TRUE) :
  Column 45 ['gadm'] of item 1 is length 0. This (and 1 other like it) has been filled with NA (NULL for list columns) to make each item uniform.
2: In setDT(ans) :
  Some columns are a multi-column type (such as a matrix column): [45]. setDT will retain these columns as-is but subsequent operations like grouping and joining may fail. Please consider as.data.table() instead which will create a new column for each embedded column.
3: In data.table::rbindlist(data, use.names = TRUE, fill = TRUE) :
  Column 46 ['gadm'] of item 1 is length 0. This (and 1 other like it) has been filled with NA (NULL for list columns) to make each item uniform.
4: In setDT(ans) :
  Some columns are a multi-column type (such as a matrix column): [46]. setDT will retain these columns as-is but subsequent operations like grouping and joining may fail. Please consider as.data.table() instead which will create a new column for each embedded column.
Called from: allocate_column(df[[var]], nrows, dfs, var)

**Comment by mgaynor1** [comment]
The fix: 

```
list <- c( "utils", "rgbif", "rbison", "rebird", "rvertnet", "ridigbio", "lubridate",
           "crul", "whisker", "jsonlite", "data.table","tibble", "wellknown")
lapply(list, install.packages)
```

error was due to versions being out of date

**Comment by sckott** [comment]
thanks for the issue @mgaynor1 !  

Sounds like you sorted it out. Nice work!
