### ISSUE TITLE
error with the limitation extractign data from OBIS

### ISSUE THREAD

**Issue by haniehsaeedi** [ropensci/spocc#244]
I am trying to extract the data from rOBIS and GBIF using Spocc package, when I increase the limit to more than 100,000 data rOBIS does not respond. I copy here my code and my error message. Do you know what causes this?
library("spocc")
out <- occ(query = c('Mollusca'), obisopts = list(areaid = 31914, startdepth = 200, enddepth = 6000), gbifopts=list(hasCoordinate=TRUE, depth='200,6000', waterBody = "South Atlantic Ocean"), from = c('gbif','obis'),limit = 14673)
dat <- occ2df(out)
Warning message:
In foo_obis(sources, x, y, s, z, hc, d, w, ds$obis) :
No records returned in OBIS for Mollusca

**Comment by hannahlowens** [comment]
Hi @haniehsaeedi--thanks for reporting this. It appears to be an issue with querying OBIS. I ran a sensitivity test using your search terms and upping the limit of records to be returned. When that limit reached 10,200 records, the API search returned  the following server status: "HTTP/1.1 400 Bad Request". This means the OBIS server cannot or will not process a request that large. I'd suggest breaking it up into smaller taxonomic groups. I will also add "Return clearer errors RE: server status" to the "To Do" list.

Here's how I ran the test, if you're curious. This loop tests the server status with a search limit starting at 100 and increasing by 100 every iteration. It breaks once the server status switches from OK to something else:
```
library(spocc)
cli <- crul::HttpClient$new(url = spocc:::obis_base(), opts = list(areaid = 31914, startdepth = 200, enddepth = 6000))

test <- 100
while (out$response_headers$status == "HTTP/1.1 200 OK") {
  args <- spocc:::sc(list(scientificname = 'Mollusca', size = test,
                          areaid = 31914, startdepth = 200, enddepth = 6000))
  print(test)
  print("ok\n")
  test <- test + 100
  out <- cli$get(path = "v3/occurrence", query = args)
}
```

**Comment by haniehsaeedi** [comment]
Hi @hannahlowens - thank you for your reply and the run test. I could imagine it has something to do with OBIS data extraction limitation. Thanks for the suggestion.

**Comment by pieterprovoost** [comment]
@hannahlowens The `size` parameter is limited to 10000, subsequent pages need to be fetched using the `after` parameter. See https://github.com/iobis/robis/blob/master/R/occurrence.R#L121

**Comment by haniehsaeedi** [comment]
Thanks, @pieterprovoost for the clarification, so this has nothing to do with the OBIS server. At the moment is not really possible to extract more than 10000 data for both GBIF and OBIS.
