### ISSUE TITLE
submit new version to CRAN?

### ISSUE THREAD

**Issue by maelle** [ropensci/spocc#257]
:wave: @hannahlowens! 

I see that since https://github.com/ropensci/spocc/commit/2769e79a674bda6a5deb36cdc08a9317200aad21 spocc no longer imports rbison which is handy since rbison is no longer maintained (it's archived on GitHub but not on CRAN yet). 

Would you have time to submit a new spocc version to CRAN? Do you need any help with that? Thank you!

**Comment by hannahlowens** [comment]
Hi @maelle,
Thanks for the poke--I just released an update to CRAN. With any luck the update will clear--checks are working locally, but something strange is happening on GitHub Actions. Any help resolving that so we don't have a big red fail badge in the readme would be VERY appreciated.

**Comment by maelle** [comment]
:wave: @hannahlowens!

I see the GHA workflow files are quite old. I'd recommend running `usethis::use_github_action_check_standard()` to overwrite the current R CMD check workflow. With a bit of luck it'll make the problem go away or at least give us an error message to work with :grin:

**Comment by sckott** [comment]
hi @hannahlowens - I just got a cran email about the `wellknown` package that I technically maintain and is on cran. They are giving 2 weeks before `wellknown` is archived - and `spocc` depends on it. There's a few places `wellknown` is used - probably it can be replaced by some other spatial package. Let me or @maelle  know if you need any help with that

p.s. @maelle in our spreadsheet we have John Waller as taking over `wellknown` but he hasn't touched it, so I don't think it will live on any longer.

**Comment by sckott** [comment]
ok, i'll try

**Comment by maelle** [comment]
thanks a lot @sckott!

**Comment by sckott** [comment]
i've told cran to archive wellknown after you submit a new version to cran

**Comment by hannahlowens** [comment]
@sckott The new version is up on CRAN. Thanks for your help getting rid of wellknown.
