### ISSUE TITLE
Pending update to ridigbio will break spocc!

### ISSUE THREAD

**Issue by mgaynor1** [ropensci/spocc#263]
Currently ridigbio returns datecollected, a field that is [randomly generated and may lack biological meaning](https://github.com/iDigBio/idb-backend/issues/229). Current use of this field is biologically meaningless, thus may skew current research leveraging dates from this field. The generated dates are also difficult to detect, as they are randomly distributed. 

We plan to update the ridigbio package to instead return "data.dwc:eventDate", "data.dwc:year", "data.dwc:month", and "data.dwc:day" - which are all text fields, rather than dates, but are not randomly generated, are directly from data providers, and may provide meaning in biological research. See [current issue](https://github.com/iDigBio/ridigbio/issues/44#issue-2072324601) and [pull request](https://github.com/iDigBio/ridigbio/pull/45).

This modification will impact the following lines:
https://github.com/ropensci/spocc/blob/59f6b3b192cd8a7bb990aab94748f3bc7b044dac/R/plugin_helpers.R#L34
https://github.com/ropensci/spocc/blob/59f6b3b192cd8a7bb990aab94748f3bc7b044dac/R/occ2df.R#L104
https://github.com/ropensci/spocc/blob/59f6b3b192cd8a7bb990aab94748f3bc7b044dac/R/plugins.r#L266

Please let us know if you have any questions.

**Comment by vijaybarve** [comment]
Will the `datecollected` field will be deprecated with immediate effect? It will be helpful to slate it for deprecation for some time and other package maintainers could make the smooth transition to `data.dwc:eventDate`.

**Comment by hannahlowens** [comment]
Resolved and on it's way to CRAN.
