### ISSUE TITLE
Support passing in sp type objects to geometry parameter

### ISSUE THREAD

**Issue by sckott** [ropensci/spocc#65]
From @jhollist https://gist.github.com/sckott/1022710622df1491e52d#comment-1221623

Seems like polygons are the obvious use case to support. Would need to take in SpatialPolygon class and extract polygons, convert to either bounding boxes or WKT's, then pass those to the API call.

**Comment by sckott** [comment]
There are a few other sp classes we could support but i think `SpatialPolygons` and `SpatialPolygonsDataFrame` are the major use cases I would think. And many sp classes aren't really possible (points, pixels, grids). 

closing, reopen if more to do, or new issue

**Comment by jhollist** [comment]
Wow, I never got around to checking out your gist...  Sorry!

But I agree that polys are the obvious use case.  You could think of ways
other features might make sense, but I think limiting to polys catches most
cases and is a perfectly legit design choice!



On Tue, Mar 24, 2015 at 8:01 PM, Scott Chamberlain <notifications@github.com
> wrote:

> Closed #65 <https://github.com/ropensci/spocc/issues/65>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/spocc/issues/65#event-264138201>.
>



-- 
Jeff W. Hollister
email: jeff.w.hollister@gmail.com
google voice: 401 326 2531
cell: 401 556 4087

**Comment by sckott** [comment]
great! hopefully we'll get some feedback if it doesn't work.

**Comment by jhollist** [comment]
I should be able to give it a go on Thurs or Fri as one check.  Better late
than never?

On Tue, Mar 24, 2015 at 8:15 PM, Scott Chamberlain <notifications@github.com
> wrote:

> great! hopefully we'll get some feedback if it doesn't work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/spocc/issues/65#issuecomment-85748375>.
>



-- 
Jeff W. Hollister
email: jeff.w.hollister@gmail.com
google voice: 401 326 2531
cell: 401 556 4087

**Comment by sckott** [comment]
Yeah, sounds great!

**Comment by jhollist** [comment]
@sckott So the gist works great.  I thought I would try it with a typical use case.  Buffering some feature of interest, and then passing the resultant poly.  This returns: 'client error: (414) Request-URI Too Long'  

Guessing this is a limitation of the API itself?  Poly I passed wasn't huge (~400 points), but they could get big.

**Comment by sckott** [comment]
@jhollist can you share the sp object so I can try to recreate the problem.

**Comment by jhollist** [comment]
Here's a gist recreating it.

https://gist.github.com/jhollist/286917bca858a4412610

Although I am now getting a different error with the buffered poly's  The simple bounding box poly works.

**Comment by sckott** [comment]
@jhollist asked about this on the GBIF mailing list, we'll see what they say

**Comment by sckott** [comment]
@jhollist heard back on this from Tim of GBIF

> My first thoughts are that even if we got it across the wire (using GET or POST) I would expect that the front ends will time out long before the SOLR index computed the query. I would recommend doing a bounding box search on GBIF, and then using geometry functions in R to "cookie cutter” the result set to the fine polygon. Is that something you think would be manageable?

Someone like you could probably do this on your own, but i think we should try to do this internally within the package for users. 

There are options for pushing a long string up via a POST request, or body of a GET request, but it sounds like they just can't easily support that right now, so I think they're saying this is our only option. 


A number of other data sources provide spatial searches. have to think about how best to do this to work across all - though perhaps GBIF is the major one people want anyway?

**Comment by jhollist** [comment]
@sckott that sounds good.  I've got a couple of functions that use `sp` to do essentially this.  Can dig them up if you like.  That being said, if `lawn` were done this'd be a nice use case for that :smile_cat:

**Comment by sckott** [comment]
would like to see how you'd solve this, e.g., given your example in the gist

I guess we already use `sp`, `rgeos`, and `rgdal` in this pkg, but would be nice to not rely on them if we could just use lawn instead - BUT - I imagine most people are used to sp spatial classes, but we could show in examples how they could simply convert from sp classes to WKT

**Comment by jhollist** [comment]
Wouldn't need `rgeos` (ha!) or `rgdal`, just `sp`.  I'll add to the gist to
pass the bbox, then select out the points that are just within the poly.



On Tue, Mar 31, 2015 at 2:01 PM, Scott Chamberlain <notifications@github.com
> wrote:

> would like to see how you'd solve this, e.g., given your example in the
> gist
>
> I guess we already use sp, rgeos, and rgdal in this pkg, but would be
> nice to not rely on them if we could just use lawn instead - BUT - I
> imagine most people are used to sp spatial classes, but we could show in
> examples how they could simply convert from sp classes to WKT
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/spocc/issues/65#issuecomment-88189670>.
>



-- 
Jeff W. Hollister
email: jeff.w.hollister@gmail.com
google voice: 401 326 2531
cell: 401 556 4087

**Comment by jhollist** [comment]
So a new gist https://gist.github.com/jhollist/b73440a1d46de3e28461

Started to dig into how to implement within spocc, but am not familiar enough to get that done quickly.  Looks like you have a lot of the functions already in there to handle the conversions to and from `sp`.

This solution would not require rgdal or rgeos.  User would probably need that if they had projected data and would need to back that out to long/lat. 

Might need to tweek the extract_sp.R function to work with multiple polygons...  Not sure.

**Comment by sckott** [comment]
thanks @jhollist i'll take a look soon

**Comment by sckott** [comment]
looking at this again

**Comment by sckott** [comment]
@jhollist The GBIF folks above suggested 

> I would recommend doing a bounding box search on GBIF, and then using geometry functions in R to "cookie cutter” the result set to the fine polygon.

Is that what your gist is trying to do? https://gist.github.com/jhollist/b73440a1d46de3e28461  I can't quite tell, but I think it is.

**Comment by jhollist** [comment]
You think I'd be able to answer that easily...

But I am pretty sure that is what it is doing.

**Comment by maelle** [comment]
Seeing this a bit late :joy: I like this feature idea, very useful!

I think it might be very similar to what @mpadge implemented for `osmdata` https://github.com/ropensci/osmdata/issues/80
